sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GVA8e+SR5VZdaPChk/iOUFE5ifvlL49slklz9etawIS/3A/7KS2uLUtB0HZHvCMNBJ7Et8sFI0hWddQ7kup5i6WBhtoig507DfdZRvew/MFc6COUNGdr87abxtQcqrQaPkzziuDSGPv02OMAM5/Ueu5Fd3+VGMQf+eXjg42ugxGvoQNPqMbVvq6x+Y/v6yLlR9oY9mN5zJBVX4pGXYWM5qT48KGcQc+5jwp0XmfhoaaWRPVaDEvfYSZFWR8z57t7pWlwJ4RoRDfD0fZ6cs7NtegW9vMefaUZ2AxXYKA5wWbRhb/YmTYSI/m4voIV6dWlLP/0a3x92N2XvOE6ClLdbMmVPJovKhsbOoMNre7Js4s/QjQ7bh9OM8rrrNp1han2L+yHi11bIMJmx3jJxMVLj3KXDBNCoHi+G74cZY7VCjLPWeRlppi8ECVH8rXx0/4PAXkxHm3XXLt605cdh5P/BgZzyVQ7nRXRsSDhU/UkDBg5azqDpjk7jIG1i5LAVbg0lmbYxNkgsZ1JfLXSlF1NpX6aFcDheCnjlaRLVBX7DKr6NB4+yZ140PmatrsAogIloVLu8JfbkLwT5EDotPTL4EXpVLwuAAnm+c1uw1OISqtUrLwFQCU+W/gtI7SsCPPgBFPxTCYf+zIE24+4TUDTbT0Kq4zjuH40/w07HSQW/Vg=

  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Notre-Dame-De-Paris_2610
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy